### PR TITLE
Proposal for issue 68: AgentOS registry

### PR DESCRIPTION
**Pull request by nickjalbert**
Addresses [Issue 68: Registery for Envs, Policies, and Agents](https://github.com/agentos-project/agentos/issues/68)

You can view versions of the proposal properly rendered:
* [v1](https://github.com/nickjalbert/design_docs/blob/36791f4ef1cf408c19cf13042bb7cc6b72cb6030/registry.rst)
* [v2](https://github.com/agentos-project/design_docs/blob/020a70a5e538b58e5e0ff269f44a7f206a7b132e/registry.rst)
* [v3](https://github.com/agentos-project/design_docs/blob/e32ff7a96eab3486a3c8bb65c1ca1df280e20434/registry.rst)
* [v4](https://github.com/agentos-project/design_docs/blob/507bfb96a1b40bef8338603a3e661681d0d622c7/registry.rst)

A fair bit of the specifics are up in the air as we think about the first class objects within AgentOS (e.g. [Issue 61:  Rationalize Policy as first class object with Agent and Env](https://github.com/agentos-project/agentos/issues/61)), but this is what my current thinking looks like after a bit of poking around at other package management systems.

I'm excited about the potential here, seems like it could become something really cool.  I think the trick will be to stay focused on a good demo/use case because it feels like this is a thing that could expand to fill any amount of time.

### CODE REVIEW

**Comment by andyk** [comment]
this looks good!

Below are a few thoughts and questions had while reading it.

shall we set up a time to meet and go over it via vid chat?

Process-wise, do you have thoughts about when would be the appropriate time to merge it in? 

- Can only 1 component of each type be installed in an agent at a time?
- What does the interface for the algorithm component look like?
- How does AgentOS locate the main code of the component within the github repo? Must all components have a well known entry point (e.g., a file called main.py)?
	- Not if we will require agents to use the acs api to interact with installed components.
- Can we add an example of a definition.py file for our example Agent Directory?
- Do I understand correctly that we will update the code generated by agentos init so that it will use the acs module?
- Do we want to design the API so that using a component from the registry looks exactly (or nearly) the same as using a hand-built component.
	- Basically, should we recommend using the same sort of composition for both composing an agent from an env, policy and algo built from scratch and composing an agent entirely from pre-built components in the registry?
- did you consider making a sub command for component type (e.g., agentos install policy dqn or agentos policy install dqn) instead of using a prefix on the component name?
- How does this relate to gym.envs.registry, if at all?
- How does this relate to how AgentOS uses MLflow for Agent Directories. Should we merge the two concepts? Or at least unify them? Maybe get rid of the dependency on MLflow?
- Use -r in requirements.txt to includes dependencies? (See https://stackoverflow.com/a/29222444 )
	- This could definitely get hairy if dependencies aren’t compatible. But perhaps that’s ok as long as the install command fails gracefully with helpful error message.
	- Or else could use separate processes and some sort of inter-process message passing?

**Comment by nickjalbert** [comment]
Thanks for the feedback and detailed questions @andyk!

> shall we set up a time to meet and go over it via vid chat?

Yeah, that'd be great.  Let's coordinate a time over signal.

> Process-wise, do you have thoughts about when would be the appropriate time to merge it in?

I'll make up a process right now:

* Write your design doc and issue a PR into the main repo and assign a reviewer
* If the reviewer:
  * Thinks the design is generally in the right ballpark but needs some minor to moderate revision and brainstorming, the PR gets an 'LGTM' and merges after any immediate nits are addressed.
  * Thinks the design needs more foundational revisions, the PR gets closed and the reviewer and reviewee sync on next steps
  * Wants to discuss over skype or in person, the PR remains open until the meeting
* Once a design doc is merged, additional updates come as new PRs
* We'll sync in planning meeting about what work to accomplish on a given design

Maybe we'll need statuses (e.g. "draft" or "accepted") or other workflows later, but I think we can keep it pretty lightweight right now.  How does that sound?


**Notes**

* I've updated the FAQ section with a bunch of your questions and my answers to them.  [Check it out here](https://github.com/agentos-project/design_docs/blob/020a70a5e538b58e5e0ff269f44a7f206a7b132e/registry.rst#faq).

* My top-line items for our meeting:
    * Let's brainstorm what types of components we want to have and their specs. Here's my initial list (with a representative function signature); let's see how useful these would be for our existing agents:
        * Environment: `step(action) -> (observation, ...)`
        * Policy: `choose(observation) -> action`
        * Learning Strategy: `train(policy) -> policy`
        * Memory: not sure exactly what the signature would look like here
    * Should we force components to be Python packages? Does that simplify requirements, installation, etc?  If so, can we just drop the proposed `definitions.py` file?
    * Review of how MLflow is used currently and how it could integrate with ACS.
    * Do we like the name ACS?  Can we think of something cuter or catchier?

**Comment by andyk** [comment]
Maybe we can make sure to add:
* a list of readable versions of the doc in the PR
* a link to the PR (for comment history) in the design doc
What do you think?

**Comment by nickjalbert** [comment]
Sounds good to me.  I see you updated the PR description with the different versions and this PR is already linked in the doc at the bottom (I'll make it more obvious).

**Comment by nickjalbert** [comment]
@andyk Updated the README in this repo with info about the process and some formatting suggestions.

I still want to pick your brain about component types and integration with MLflow.  However, I don't think this deeply affects much of the initial work on this design.  If you agree, I propose you approve the review and we merge.  If not, I'm happy to meet again and figure out next steps.

**Review by andyk — APPROVED** [review]
This is looking good! Let’s start dev!

**Comment by andyk** [comment]
@nickjalbert i had two more thoughts today:

* should we spend stone time brainstorming around the name? I like that acs is short and straightforward. I don’t like that it isn’t easy to pronounce as one syllable. I wonder if using the acronym acs as the module name where the full name would be`agentos.acs` is a little redundant (since the a in acs stands for agentos) and not as descriptive (because it is an acronym) as something like `agentos.reg` or `agentos.registry`. On the other hand `pip` and `apt` are both acronyms (pip is even recursive). We could also use a cute short name in the spirit of `brew` (which is metaphorical and has cute names for related concepts like tapping kegs, etc.), `gem` (which ties into the ruby theme), `port`. Anyway, I’m nota hard no on acs if you are attached to it, but maybe we can brainstorm a bit more?
* I wasn’t sure exactly what the design doc intends means when it talks about merging requirements. If it means merging then into a single file inside the agent directory at component install time, that doesn’t seem future proof (vs keeping them in separate files) for uninstalling and upgrading components. I had a terse bullet about this in my original round of feedback but didn’t see anywhere that you addressed yet (though you might have and I just missed it).

I’m super excited about ACS and can’t wait to see V0!

**Comment by nickjalbert** [comment]
>  full name would be `agentos.acs` is a little redundant

Don't want to "RISC computer" ourselves, eh?  I am not attached to `acs`; let's see if we can come up with something more clever!

>  merging requirements

Yeah, I didn't have much intuition about how to design this, and I think the point about uninstalling is a good one.  I'll update the doc to clarify that we keep the requirements separated (but, ideally, with some linking or similar to make it straightforward to install all requirements from the top-level agent directory by hand.)

**Comment by nickjalbert** [comment]
Just FYI, notes from a meeting Andy and I had on 2/3 (I believe between v2 and v3):

 * Andy will take a look at the updated FAQs sometime tomorrow and we'll talk tomorrow.
 * I'll update the proposal to reflect our discussion tonight or tomorrow morning.
 * We discussed the idea of installing components and how that changes shortcuts like `acs.environment`. 
   * All components are always accessible through their full names (e.g. `acs.environment.cartpole`)
   * You will be prompted if you install multiple components of the same type about which one should be used as the shortcut (for example, `acs.environment`).
 * We decided  on an initial version of the registry entry where each entry contains a dictionary that points to the (github_url, hash, fully_qualified_class_name, requirements_file) for the component so no special files (i.e. no `definitions.py`) are needed in the component repo itself.
   * We need to think through issues around mismatches between the registry and the component repo before we open up registration to the public (perhaps we want to still require an agentos.ini file even though it wouldn't be strictly necessary in this first version)

**Pull request merged**
